## Assetic Configuration
assetic:
    debug:          %kernel.debug%  
    use_controller: false
    bundles:        [ LeagueVillageBundle ]    
    filters:
        cssrewrite: ~
#        yui_css:
#            jar: /usr/share/yui-compresor/yui-compresor.jar