league_village:
    resource: "@LeagueVillageBundle/Resources/config/routing.yml"
    prefix:   /

themes_bootstrap:
    resource: "@ThemesBootstrapBundle/Resources/config/routing.yml"
    prefix: /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
