themes_bootstrap:
    resource: "@ThemesBootstrapBundle/Resources/config/routing.yml"
    prefix: /
    
league_village:
    resource: "@LeagueVillageBundle/Resources/config/routing.yml"
    prefix:   /