league_village_homepage:
    path:     /
    defaults: { _controller: LeagueVillageBundle:Default:index }

league_village:
    path:     /village/{id}
    defaults: { _controller: LeagueVillageBundle:Village:index }
    
contact_new:
    path:   /contact
    defaults: { _controller: LeagueVillageBundle:Default:contact }
    
contact_success:
    path: /
    defaults: { _controller: LeagueVillageBundle:Default:response }
    
send_ok:
    path: /
    defaults: { _controller: LeagueVillageBundle:Default:send_ok }