league_village_homepage:
    path:     /
    defaults: { _controller: LeagueVillageBundle:Default:index }
    
contact_new:
    path: /contact
    defaults: { _controller: LeagueVillageBundle:Default:contact }
    
contact_success:
    path: /contact_sucess
    defaults: { _controller: LeagueVillageBundle:Default:response }
    
portal_homepage:
    path: /portal
    defaults: { _controller: LeagueVillageBundle:Portal:index }
    
portal_village:
    path: /village/{page}
    defaults: { _controller: LeagueVillageBundle:Portal:villages, page:1 }